### ISSUE TITLE
balenaEtcher

### ISSUE THREAD

**Issue by bretthl** [anphsw/memtest86-#24]
On you web sight you suggest balenaEtcher for creating a bootable USB.  balenaEtcher does not work properly.  I suggest you change your recommendation to something else (perhaps Gnome Multiwriter).  balenaEtcher is garbage.

**Comment by anphsw** [comment]
Sorry, this project don't have any references to balenaEtcher in code. Reopen this issue with more specific info.

**Comment by bretthl** [comment]
https://memtest.org/  specifically mentions balenaEtcher.  I highly recommend removing reference to this questionable application.

**Comment by anphsw** [comment]
I have no control over this website. Perhabs original author does.
Please address this issue to https://github.com/memtest86plus/memtest86plus/ project.
